# Generated by Django 5.2.4 on 2025-07-23 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
